char *ename[] =
     {
     "",                      /*  00  */
     "Max Digits Rcvd     ",  /*  01  */
     "Term Digit ONE      ",  /*  02  */
     "Line Stop           ",  /*  03  */
     "DOS Error           ",  /*  04  */
     "Max Bytes           ",  /*  05  */
     "",                      /*  06  */
     "Max Seconds         ",  /*  07  */
     "Offhook Complete    ",  /*  08  */
     "Dial Complete       ",  /*  09  */
     "Max Silence         ",  /*  0A  */
     "EOF reached         ",  /*  0B  */
     "Loop Signal Term    ",  /*  0C  */
     "",                      /*  0D  */
     "Onhook Complete     ",  /*  0E  */
     "Digit Received      ",  /*  0F  */
     "Loop Event          ",  /*  10  */
     "",                      /*  11  */
     "Call Progress Rcvd  ",  /*  12  */
     "",                      /*  13  */
     "",                      /*  14  */
     "Rings Received      ",  /*  15  */
     "Silence State Chg   ",  /*  16  */
     "",                      /*  17  */
     "",                      /*  18  */
     "",                      /*  19  */
     "",                      /*  1A  */
     "",                      /*  1B  */
     "",                      /*  1C  */
     "Term Digit TWO      ",  /*  1D  */
     "IDD Exceeded        ",  /*  1E  */
     "Max NonSilence      "   /*  1F  */
     };
char *errorstrings[] =
    {
    "OK                   ",  /* 00 */
    "",                       /* 01 */
    "Digit Buffer Empty   ",  /* 02 */
    "System Active        ",  /* 03 */
    "System Not Active    ",  /* 04 */
    "",                       /* 05 */
    "Invalid function     ",  /* 06 */
    "",                       /* 07 */
    "",                       /* 08 */
    "Invalid line number  ",  /* 09 */
    "Line is busy         ",  /* 0A */
    "",                       /* 0B */
    "",                       /* 0C */
    "",                       /* 0D */
    "",                       /* 0E */
    "No terminating option",  /* 0F */
    "Training Error       "   /* 10 */
    };

